language: node_js
node_js:
  - "5.0"
  - "node"
sudo: false
cache:
   directories:
     - node_modules
     - chrome-linux
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./test/download-chrome.sh
  - start-stop-daemon --start --background --exec $(pwd)/chrome-linux/chrome -- --remote-debugging-port=9222 --no-first-run --enable-gpu-benchmarking --user-data-dir="/tmp/lighthouse-profile" --disable-setuid-sandbox "about:blank"
  - sleep 5
